"""add delivery date and saved locations

Revision ID: 9b3fadbb11e4
Revises: e0f408f76920
Create Date: 2026-07-02 16:13:54.605101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3fadbb11e4'
down_revision = 'e0f408f76920'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('manager_id', sa.String(length=36), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('service_time_seconds', sa.Integer(), nullable=False),
    sa.Column('address_label', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_locations_manager_id'), 'saved_locations', ['manager_id'], unique=False)
    op.add_column('jobs', sa.Column('delivery_date', sa.Date(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'options', ['published_option_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'delivery_date')
    op.drop_index(op.f('ix_saved_locations_manager_id'), table_name='saved_locations')
    op.drop_table('saved_locations')
    # ### end Alembic commands ###
