"""add created_at to job_stops

Revision ID: bf29acd4765d
Revises: 9b3fadbb11e4
Create Date: 2026-07-02 17:12:42.360711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf29acd4765d'
down_revision = '9b3fadbb11e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_stops', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_stops', 'created_at')
    # ### end Alembic commands ###
