"""initial schema

Revision ID: e0f408f76920
Revises: 
Create Date: 2026-07-01 18:11:52.585816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0f408f76920'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'COURIER', name='userrole'), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('courier_invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('manager_id', sa.String(length=36), nullable=False),
    sa.Column('courier_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='invitestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courier_invites_courier_id'), 'courier_invites', ['courier_id'], unique=False)
    op.create_index(op.f('ix_courier_invites_manager_id'), 'courier_invites', ['manager_id'], unique=False)
    op.create_index('ix_one_pending_invite_per_pair', 'courier_invites', ['manager_id', 'courier_id'], unique=True, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('courier_profiles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('manager_id', sa.String(length=36), nullable=True),
    sa.Column('default_start_time_seconds', sa.Integer(), nullable=False),
    sa.Column('default_end_time_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_courier_profiles_manager_id'), 'courier_profiles', ['manager_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('manager_id', sa.String(length=36), nullable=False),
    sa.Column('depot_lat', sa.Float(), nullable=False),
    sa.Column('depot_lon', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'OPTIONS_READY', 'PUBLISHED', 'ARCHIVED', name='jobstatus'), nullable=False),
    sa.Column('published_option_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['published_option_id'], ['options.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_manager_id'), 'jobs', ['manager_id'], unique=False)
    op.create_table('job_couriers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('courier_id', sa.String(length=36), nullable=False),
    sa.Column('start_time_seconds', sa.Integer(), nullable=False),
    sa.Column('end_time_seconds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['courier_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'courier_id', name='uq_job_courier')
    )
    op.create_index(op.f('ix_job_couriers_courier_id'), 'job_couriers', ['courier_id'], unique=False)
    op.create_index(op.f('ix_job_couriers_job_id'), 'job_couriers', ['job_id'], unique=False)
    op.create_table('job_stops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('service_time_seconds', sa.Integer(), nullable=False),
    sa.Column('address_label', sa.String(length=255), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_stops_job_id'), 'job_stops', ['job_id'], unique=False)
    op.create_table('options',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('requested_courier_count', sa.Integer(), nullable=True),
    sa.Column('courier_count_mode', sa.Enum('EXACT', 'MAX', name='couriercountmode'), nullable=True),
    sa.Column('algorithm_key', sa.String(length=64), nullable=False),
    sa.Column('algorithm_tier', sa.String(length=32), nullable=False),
    sa.Column('total_duration_seconds', sa.Float(), nullable=False),
    sa.Column('feasible', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'STALE', 'PUBLISHED', 'SUPERSEDED', name='optionstatus'), nullable=False),
    sa.Column('parent_option_id', sa.String(length=36), nullable=True),
    sa.Column('stops_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['parent_option_id'], ['options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_options_job_id'), 'options', ['job_id'], unique=False)
    op.create_table('option_courier_routes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('option_id', sa.String(length=36), nullable=False),
    sa.Column('job_courier_id', sa.String(length=36), nullable=False),
    sa.Column('total_travel_seconds', sa.Float(), nullable=False),
    sa.Column('total_service_seconds', sa.Float(), nullable=False),
    sa.Column('total_duration_seconds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_courier_id'], ['job_couriers.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_courier_routes_job_courier_id'), 'option_courier_routes', ['job_courier_id'], unique=False)
    op.create_index(op.f('ix_option_courier_routes_option_id'), 'option_courier_routes', ['option_id'], unique=False)
    op.create_table('option_unassigned_stops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('option_id', sa.String(length=36), nullable=False),
    sa.Column('job_stop_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['job_stop_id'], ['job_stops.id'], ),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_unassigned_stops_job_stop_id'), 'option_unassigned_stops', ['job_stop_id'], unique=False)
    op.create_index(op.f('ix_option_unassigned_stops_option_id'), 'option_unassigned_stops', ['option_id'], unique=False)
    op.create_table('option_route_stops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('option_courier_route_id', sa.String(length=36), nullable=False),
    sa.Column('job_stop_id', sa.String(length=36), nullable=False),
    sa.Column('sequence_index', sa.Integer(), nullable=False),
    sa.Column('leg_travel_seconds', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['job_stop_id'], ['job_stops.id'], ),
    sa.ForeignKeyConstraint(['option_courier_route_id'], ['option_courier_routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_route_stops_job_stop_id'), 'option_route_stops', ['job_stop_id'], unique=False)
    op.create_index(op.f('ix_option_route_stops_option_courier_route_id'), 'option_route_stops', ['option_courier_route_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_option_route_stops_option_courier_route_id'), table_name='option_route_stops')
    op.drop_index(op.f('ix_option_route_stops_job_stop_id'), table_name='option_route_stops')
    op.drop_table('option_route_stops')
    op.drop_index(op.f('ix_option_unassigned_stops_option_id'), table_name='option_unassigned_stops')
    op.drop_index(op.f('ix_option_unassigned_stops_job_stop_id'), table_name='option_unassigned_stops')
    op.drop_table('option_unassigned_stops')
    op.drop_index(op.f('ix_option_courier_routes_option_id'), table_name='option_courier_routes')
    op.drop_index(op.f('ix_option_courier_routes_job_courier_id'), table_name='option_courier_routes')
    op.drop_table('option_courier_routes')
    op.drop_index(op.f('ix_options_job_id'), table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_job_stops_job_id'), table_name='job_stops')
    op.drop_table('job_stops')
    op.drop_index(op.f('ix_job_couriers_job_id'), table_name='job_couriers')
    op.drop_index(op.f('ix_job_couriers_courier_id'), table_name='job_couriers')
    op.drop_table('job_couriers')
    op.drop_index(op.f('ix_jobs_manager_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_courier_profiles_manager_id'), table_name='courier_profiles')
    op.drop_table('courier_profiles')
    op.drop_index('ix_one_pending_invite_per_pair', table_name='courier_invites', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_courier_invites_manager_id'), table_name='courier_invites')
    op.drop_index(op.f('ix_courier_invites_courier_id'), table_name='courier_invites')
    op.drop_table('courier_invites')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
